---
title: "Hyponatrmia audit"
output: html_notebook
---

```{r}
#Load the tidyverse

library(tidyverse)

```

```{r}
#load the other libraries

<<<<<<< HEAD
library(lubridate)
library(gghighlight)
library(ggthemes)
library(forecast)
=======
<<<<<<< HEAD
library(lubridate)
library(gghighlight)
library(ggthemes)
=======
#Currently blank
>>>>>>> f540fe8b8355a144562338d067f582600d5ad48e
>>>>>>> 4766c1ca7f59419e439a0e4adc26f2c5d48db514

```

```{r}
# Declare the variables

Column_names <- c(
  "NHI",
  "Date",
  "Na"
)

```

```{r}
#Load th4e data

Sodium_ED <- read_csv("/home/greig/R-projects/Clinical_audits/Sodium/Hyponatremia/Sodium_EMER_2017.csv", skip = 1, col_names = Column_names)

```

```{r}
#tidy the data

Sodium_ED$Na <- as.integer(Sodium_ED$Na)
Sodium_ED$Date <- lubridate::dmy_hms(Sodium_ED$Date)

Sodium_ED <- Sodium_ED %>% 
  filter(!is.na(Na))

glimpse(Sodium_ED)
```

```{r}
ggplot(Sodium_ED, aes (x = Na)) +
  geom_bar(fill = "red") +
  labs(title = "Frequency distribution of ED Sodium values", x = "Sodium values") +
  gghighlight(Na < 124, unhighlighted_colour = "blue") +
  scale_fill_viridis_d() +
  theme_economist_white() +
    theme(legend.position = "none")
```

```{r}
Low_Na <- Sodium_ED %>% 
  filter(Na < 124)
```

```{r, message=FALSE, warning=FALSE}
Sodium_ED <- Sodium_ED %>% 
  mutate(Week = week(Date))

Na_week <- Sodium_ED %>% 
  group_by(Week) %>% 
  summarise(Count = n(), Mean = mean(Na))

Na_week <- Na_week %>%
  filter(Week != 53)

ggplot(Na_week, aes(x = Week, y = Count)) +
  geom_line() +
  geom_smooth() +
  theme_economist_white()

ggplot(Na_week, aes(x = Week, y = Mean)) +
  geom_line() +
  geom_smooth() +
  theme_economist_white()

```
